import "./globals.css";

export const metadata = {
  title: "Todo App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning className="bg-gray-100">
        {children}
      </body>
    </html>
  );
}
